books/urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [
    path('', views.books_list, name="catalog"),
    # path('new-review/', views.review_new, name="new-review"),
    path('<slug:book_slug>/review/', views.new_review, name="new-review"),
    path('<slug:slug>', views.book_page, name="page"),
]

quill/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage),
    path('faq/', views.faq, name='faq'),
    path('about/', views.about, name='about'),
    path('books/', include('books.urls')),
    path('users/', include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import register_view, login_view, logout_view

app_name = 'users'

urlpatterns = [
    path('register/', register_view, name="register"),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
]

templates/about.html
{% extends "layout.html" %} 

{% block title %}
    about
{% endblock %}

{% block content %}
    <h1>about</h1>
{% endblock  %}

templates/faq.html
{% extends "layout.html" %} 

{% block title %}
    FAQ - Quill
{% endblock %}

{% block content %}
<section class="container mx-auto p-8">
  <div class="mt-4">
    <h1 class="text-3xl font-bold text-gray-800 mb-8 text-center">Frequently Asked Questions</h1>
  </div>

  <div class="max-w-3xl mx-auto space-y-8">
    <div class="faq-item space-y-8">
      <h3 class="text-xl font-semibold text-yellow-500">Will Seven Seas be publishing any more danmei series?</h3>
      <p class="text-gray-700 mt-2">
          If our current books continue to sell well, that increases the chance
          that other danmei will be published officially in English! We're
          thrilled to already be bringing works over from multiple beloved
          authors. Thank you for your support! And feel free to suggest any
          licenses in our monthly survey, which can be found via our main
          website.
      </p>
    </div>
    <hr class="border-gray-300">

    <div class="faq-item">
      <h3 class="text-xl font-semibold text-yellow-500">Will you censor anything?</h3>
      <p class="text-gray-700 mt-2">
          We’re working closely with respected translators in the danmei
          community to ensure a smooth, faithful translation of the original
          works given to us by the rights holders, with all content
          included—including some material not available in other editions (such
          as short stories and sex scenes).
      </p>
    </div>
    <hr class="border-gray-300">

      <div class="faq-item">
        <h3 class="text-xl font-semibold text-yellow-500">Will you include all the short stories and bonus chapters?</h3>
        <p class="text-gray-700 mt-2">
            Our editions will include all the material given to us by the rights
            holders for publication in English. In most cases, that will include
            short stories previously seen in print and digital editions, although
            there are some exceptions (such as a story exclusive to another
            publication).
        </p>
      </div>
      <hr class="border-gray-300">

      <div class="faq-item">
        <h3 class="text-xl font-semibold text-yellow-500">Will the books have content warnings/ratings?</h3>
        <p class="text-gray-700 mt-2">
          Seven Seas does not include specific content warnings on novels.
          However, Seven Seas does print age ratings on the back of books with a
          high level of adult content, such as books rated Mature.
        </p>
      </div>
      <hr />

      <div class="faq-item">
        <h3 class="text-xl font-semibold text-yellow-500">Why has the release date of a book changed?</h3>
        <p class="text-gray-700 mt-2">
          There are many reasons why release dates may change, including factors
          that are outside of our control. We're working hard to get
          high-quality translations and illustrations of your favorite books out
          to you—thank you for your patience!
        </p>
      </div>
      <hr />

      <div class="faq-item">
        <h3 class="text-xl font-semibold text-yellow-500">Does this support the creator?</h3>
        <p class="text-gray-700 mt-2">
          These are official English editions licensed from the rights holders,
          so every new copy purchased—ebook or paperback—will support the
          original creator, like the official editions in various other
          languages.
        </p>
      </div>
      <hr />

      <div class="faq-item">
        <h3 class="text-xl font-semibold text-yellow-500">Is the artwork "official"?</h3>
        <p class="text-gray-700 mt-2">
          Yes! All the artwork published in our editions—from the character
          designs to the logos to the interior illustrations—must receive full
          approval from the rights holders.
        </p>
      </div>
      <hr />

      <div class="faq-item">
        <h3 class="text-xl font-semibold text-yellow-500">
          Will you hire me to translate, edit, or draw for a danmei series?
        </h3>
        <p class="text-gray-700 mt-2">
          Please stay tuned to our Jobs page to see when we're hiring. You can
          also share your resume or portfolio for consideration via the contact
          form on our main website. Please note that Seven Seas cannot reply to
          all submissions, and emailing us does not guarantee consideration.
        </p>
      </div>
      <hr />

      <div class="faq-item">
        <h3 class="text-xl font-semibold text-yellow-500">Will there be an audiobook?</h3>
        <p class="text-gray-700 mt-2">
          No audiobooks are available at this time, but we will be sure to make
          an announcement if that changes. You can find all of our current
          audiobooks under the Seven Seas Siren imprint here.
        </p>
      </div>
      <hr />

      <div class="faq-item">
        <h3 class="text-xl font-semibold text-yellow-500">What about the manhua/comics?</h3>
        <p class="text-gray-700 mt-2">
          Seven Seas is releasing the Grandmaster of Demonic Cultivation
          manhua/comic as well, with multiple volumes already available. More
          details here.
        </p>
      </div>
      <hr />

      <div class="faq-item">
        <h3 class="text-xl font-semibold text-yellow-500">Can we order the books directly from you?</h3>
        <p class="text-gray-700 mt-2">
          Yes! Along with being distributed by Penguin Random House, the largest
          distributor in North America—who provides service to many retailers
          and bookstores around the world—we also recently launched the GOMANGA
          Store!
        </p>
      </div>
    </div>
  </div>
</section>

{% endblock %}

templates/index.html
{% extends "layout.html" %}

{% block title %} Home - Quill {% endblock %} 

{% block content %}
<section class="hero bg-yellow-50 text-center py-20">
  <div class="container mx-auto">
    <h1 class="text-4xl font-extrabold text-gray-800">Home | Quill</h1>
    <p class="text-lg text-gray-600 mt-4">Discover, Read, and Share your Favorite Books</p>
    <a href="{% url 'books:catalog' %}" class="mt-8 inline-block bg-yellow-400 text-white font-semibold py-3 px-8 rounded-lg shadow-lg transition duration-300 hover:bg-yellow-500">
      Browse Books
    </a>
  </div>
</section>

<main>
  <section class="bg-white py-16">
    <div class="container mx-auto">
      <h2 class="text-3xl font-bold text-center text-gray-800 mb-8">Explore by Genre</h2>
      <div class="flex flex-wrap justify-center space-x-4">
          {% for genre in popular_genres %}
            <a href="{% url 'books:catalog' %}?genre={{ genre.id }}" class="text-xl font-semibold text-white">
              <div class="max-w-xs w-60 bg-yellow-400 text-center py-4 px-6 rounded-lg shadow-md mb-4 transition duration-300 hover:bg-yellow-500">
                {{ genre.title }}
              </div>
            </a>
          {% empty %}
            <p>No genres to display.</p>
          {% endfor %}
      </div>
    </div>
  </section>

  <section class="bg-gray-100 py-16">
    <div class="container mx-auto">
      <h2 class="text-3xl font-bold text-center text-gray-800 mb-8">Recent Releases</h2>
      <div class="flex flex-wrap justify-center">
        {% for book in recent_books %}
        <article class="max-w-xs w-60 bg-white rounded-lg shadow-md m-4 p-6 book-card">
          <a href="{% url 'books:page' slug=book.slug %}">
            <img
              class="w-full h-64 object-cover rounded-t-lg"
              src={{book.cover.url}}
              alt="{{book.title}}" />
            <div class="p-4 text-center">
              <h3 class="text-xl font-semibold text-gray-700">{{book.title}}</h3>
              <p class="text-gray-500">{{ book.author }}</p>
              <p class="text-gray-600 mt-2">${{ book.price }}</p>
            </div>
          </a>
        </article>
        {% empty %}
          <p>No recent releases available.</p>
        {% endfor %}
      </div>
    </div>
  </section>

  <section class="bg-white py-16">
    <div class="container mx-auto">
      <h2 class="text-3xl font-bold text-center text-gray-800 mb-8">Coming Soon</h2>
      <div class="flex flex-wrap justify-center">
        {% for book in coming_soon_books %}
          <article class="max-w-xs w-60 bg-white rounded-lg shadow-md m-4 p-6 book-card">
            <a href="{% url 'books:page' slug=book.slug %}">
              <img
                class="w-full h-64 object-cover rounded-t-lg"
                src={{book.cover.url}}
                alt="{{book.title}}" />
              <div class="p-4 text-center">
                <h3 class="text-xl font-semibold text-gray-700">{{book.title}}</h3>
                <p class="text-gray-500">{{book.author}}</p>
                <p class="text-sm text-yellow-500 mt-2">Available on {{book.publication_date}}</p>
              </div>
            </a>
          </article>
        {% empty %}
          <p>no</p>
        {% endfor %}
      </div>
    </div>
  </section>
  
</main>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} default title {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/tailwind.css'%}" />
    <link rel="stylesheet" href="{% static 'css/style.css'%}" />
    <script src="{% static 'js/main.js' %}" defer></script>
  </head>
  <body>
    <header class="header bg-white shadow-md z-10 py-3">
      <div class="container mx-auto flex justify-between items-center">
        <a href="/" class="text-3xl font-extrabold text-yellow-500">Quill</a>
        <nav class="flex justify-between items-center space-x-4">
          <a href="{% url 'books:catalog' %}" class="text-gray-700 transition duration-300 hover:text-yellow-500">Catalog</a>
          <a href="{% url 'about' %}" class="text-gray-700 transition duration-300 hover:text-yellow-500">About</a>
          <a href="{% url 'faq' %}" class="text-gray-700 transition duration-300 hover:text-yellow-500">FAQ</a>

          <form action="{% url 'books:catalog' %}" method="get" class="search-form">
            <input
              type="text"
              name="search"
              placeholder="Search books..."
              value="{{ request.GET.search }}"
              aria-label="Search books"
              class="search-input" />
            <button type="submit" class="search-button">
              <img
                src="{% static 'search.svg' %}"
                alt="search-icon"
                width=17 >
            </button>
          </form>

          {% if user.is_authenticated %}
          <form class="inline" action="{% url 'users:logout' %}" method="post">
            {% csrf_token %}
            <button class="inline-block bg-yellow-400 text-white font-semibold py-3 px-6 rounded-lg shadow-lg transition duration-300 hover:bg-yellow-500">Log Out</button>
          </form>
          {% else %}
          <a href="{% url 'users:register' %}" class="text-gray-700 transition duration-300 hover:text-yellow-500">Registration</a>
          <a href="{% url 'users:login' %}" class="text-gray-700 transition duration-300 hover:text-yellow-500">Log In</a>
          {% endif %}
        </nav>
      </div>
    </header>
    <main>{% block content %} {% endblock %}</main>
    <footer class="footer bg-gray-800 py-8 text-gray-400">
      <div class="container mx-auto text-center">
          <p>&copy; 2024 Quill. All rights reserved.</p>
          <nav class="space-x-4 mt-4">
              <a href="/" class="hover:text-yellow-500">Home</a>
              <a href="{% url 'about' %}" class="hover:text-yellow-500">About</a>
              <a href="{% url 'faq' %}" class="hover:text-yellow-500">FAQ</a>
          </nav>
      </div>
  </footer>
  </body>
</html>