books/urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [
    path('', views.books_list, name="catalog"),
    # path('new-review/', views.review_new, name="new-review"),
    path('<slug:book_slug>/review/', views.new_review, name="new-review"),
    path('<slug:slug>', views.book_page, name="page"),
]

quill/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage),
    path('faq/', views.faq, name='faq'),
    path('about/', views.about, name='about'),
    path('books/', include('books.urls')),
    path('users/', include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import register_view, login_view, logout_view

app_name = 'users'

urlpatterns = [
    path('register/', register_view, name="register"),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
]

books/models.py
from django.db import models
from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator
from datetime import datetime

# Create your models here.

class Book(models.Model):
    title = models.CharField(max_length=255)
    author = models.ForeignKey('Author',on_delete=models.CASCADE, null=True, blank=True)
    isbn = models.BigIntegerField(unique=True)
    genre = models.ForeignKey('Genre',on_delete=models.CASCADE, null=True, blank=True)
    publisher = models.ForeignKey('Publisher',on_delete=models.CASCADE, null=True, blank=True)
    publication_date = models.DateField(null=True, blank=True)
    description = models.TextField()
    price = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True)
    language = models.CharField(max_length=255)
    page_count = models.IntegerField(default='not_found.png', null=True, blank=True)
    cover = models.ImageField(upload_to='book_covers/', null=True, blank=True)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title


class Author(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    biography = models.TextField()
    birth_date = models.DateField(null=True, blank=True)
    death_date = models.DateField(null=True, blank=True)
    nationality = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Publisher(models.Model):
    title = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    year_founded = models.PositiveIntegerField(null=True, blank=True, validators=[
            MinValueValidator(0),
            MaxValueValidator(datetime.now().year)
        ])
    description = models.TextField()
    contact_phone = models.CharField(max_length=25, null=True, blank=True)
    site = models.CharField(max_length=255, null=True, blank=True)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title


class Genre(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    target_audience = models.CharField(max_length=255)
    literature_type = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title


class Review(models.Model):
    book = models.ForeignKey('Book', on_delete=models.CASCADE, null=True, blank=True, related_name="reviews")
    # user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    rating = models.PositiveIntegerField(choices=[(i, i) for i in range(1, 6)])
    # rating = models.PositiveIntegerField(null=True, blank=True, validators=[
    #         MinValueValidator(0),
    #         MaxValueValidator(5)
    #     ])
    review_text = models.TextField(null=True, blank=True)
    review_date = models.DateField(auto_now_add=True, null=True, blank=True)
    recommendation = models.BooleanField(null=True, blank=True)
    # slug = models.SlugField(unique=True)

    def __str__(self):
        return f"{self.user} review on {self.book.title} - {self.rating} stars"

books/forms.py
from django import forms
from .models import Review

class ReviewForm(forms.ModelForm):
    
    class Meta:
        model = Review
        fields = ['rating', 'review_text', 'recommendation']

books/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from django_filters import rest_framework as filters
from .models import Book, Review
from .filters import BookFilter
from .forms import ReviewForm
from django.contrib.auth.decorators import login_required

def chunked(iterable, size):
    chunk = []
    for item in iterable:
        chunk.append(item)
        if len(chunk) == size:
            yield chunk
            chunk = []
    if chunk:  
        yield chunk


# Create your views here.
def books_list(request):
    books = Book.objects.all()
    book_filter = BookFilter(request.GET, queryset=books)

    search_query = request.GET.get('search', '')
    if search_query:
        books = books.filter(
            Q(title__icontains=search_query) |
            Q(description__icontains=search_query) |
            Q(author__first_name__icontains=search_query) |
            Q(author__last_name__icontains=search_query)
        )

    sort_by = request.GET.get('sort_by', 'publication_date')
    order = request.GET.get('order', 'desc') 
    if sort_by in ['title', 'price', 'publication_date']:
        if order == 'desc':
            sort_by = f'-{sort_by}'
        books = book_filter.qs.filter(pk__in=books).order_by(sort_by)
    else:
        books = book_filter.qs.filter(pk__in=books)
    
    sorted_books = list(chunked(books, 5))

    return render(request, 'books/books_list.html', {'sorted_books': sorted_books, 'filter': book_filter, 'sort_by': sort_by, 'order': order, 'search_query': search_query})

def book_page(request, slug):
    book = Book.objects.get(slug=slug)
    return render(request, 'books/book_page.html', {'book' : book})

@login_required(login_url="/users/login/")
def review_new(request):
    return render(request, 'books/review_new.html')

@login_required
def new_review(request, book_slug):
    book = get_object_or_404(Book, slug=book_slug)

    if request.method == "POST":
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.user = request.user
            review.book = book
            review.save()
            return redirect('books:page', slug=book.slug)
    else:
        form = ReviewForm()
    return render(request, 'books/new_review.html', {'form': form, 'book': book})

books/templates/books/book_page.html
{% extends "layout.html" %}

{% block title %}
    {{ book.title }} - Quill
{% endblock %}

{% block content %}
<div class="container mx-auto mt-8">
  <section class="book-details mb-8">
    <img
      class="rounded-lg shadow-lg"
      src="{{book.cover.url}}"
      alt="{{book.title}}"
    />
    <div>
      <h1 class="text-4xl font-bold text-gray-800 mb-4">{{ book.title }}</h1>
      <p>
        <span class="font-semibold text-yellow-500">Author:</span> {{book.author }}
      </p>
      <p class="text-lg text-gray-600 mb-2">
        <span class="font-semibold text-yellow-500">Publication Date:</span> {{book.publication_date|date:"F j, Y" }}
      </p>
      <p class="text-lg text-gray-600 mb-2">
        <span class="font-semibold text-yellow-500">Page Count:</span> {{ book.page_count }}
      </p>
      <p class="text-lg text-gray-600 mb-2">
        <span class="font-semibold text-yellow-500">ISBN:</span> {{ book.isbn }}
      </p>
      <p class="text-lg text-gray-600 mb-4">
        <span class="font-semibold text-yellow-500">Price:</span> ${{ book.price }}
      </p>
      <p class="text-gray-700 leading-relaxed">{{ book.description }}</p>
    </div>
  </section>

  <section class="mb-8">
    <h2 class="text-2xl font-bold text-gray-800 mb-4">Reviews</h2>
    {% if user.is_authenticated %}
    <div class="mt-6">
      <a
        href="{% url 'books:new-review' book_slug=book.slug %}"
        class="mb-6 inline-block bg-yellow-400 text-white font-semibold py-3 px-8 rounded-lg shadow-lg transition duration-300 hover:bg-yellow-500"
        >Write a Review</a>
    </div>
    {% else %}
    <p class="text-gray-700 mt-8">
      <a href="{% url 'users:login' %}" class="text-yellow-500 hover:underline"
        >Log in</a
      >
      to write a review.
    </p>
    {% endif %} 
    
    {% for review in book.reviews.all %}
    <div class="bg-white shadow-md rounded-lg p-4 mb-4 border-l-4 border-yellow-500" >
      <p class="text-gray-800 font-semibold">
        {{ review.user.username }} rated it {{ review.rating }} stars
      </p>
      <p class="text-gray-700 my-2">{{ review.review_text }}</p>
      <p class="text-gray-500 text-sm">
        Posted on {{ review.review_date|date:"F j, Y" }}
      </p>
    </div>
    {% empty %}
      <p class="text-gray-500 mt-4">No reviews yet. Be the first to review!</p>
    {% endfor %}
  </section>
</div>
{% endblock %}

books/templates/books/books_list.html
{% extends "layout.html" %} 

{% block title %}
  Catalog - Quill
{% endblock %}

{% block content %}
<section class="container mx-auto py-8 px-4">
  <div class="mb-4">
    <h1 class="text-3xl font-extrabold text-gray-800 mb-8 text-center">Books Catalog</h1>
  </div>

  <form method="get" class="flex flex-wrap items-center justify-center mb-8 space-x-4">
    {{filter.form.as_p}}

    <div class="space-y-2 text-center sorting">
      <label for="sort_by" class="text-gray-700 font-medium labl">Sort By:</label>
      <select name="sort_by" id="sort_by" class="buttons_fire w-full select-sort">
        <option value="title" {% if sort_by == 'title' %}selected{% endif %}>Title</option>
        <option value="price" {% if sort_by == 'price' %}selected{% endif %}>Price</option>
        <option value="publication_date" {% if sort_by == 'publication_date' %}selected{% endif %}>Publication Date</option>
      </select>
    </div>

    <div class="space-y-2 text-center sorting">
      <label for="order" class="text-gray-700 font-medium labl">Order:</label>
      <select name="order" id="order" class="buttons_fire w-full select-sort">
        <option value="asc" {% if order == 'asc' %}selected{% endif %}>Ascending</option>
        <option value="desc" {% if order == 'desc' %}selected{% endif %}>Descending</option>
      </select>
    </div>

    <div class="w-full flex justify-center">
      <button type="submit" class="mt-8 inline-block bg-yellow-400 text-white font-semibold py-3 px-8 rounded-lg shadow-lg transition duration-300 hover:bg-yellow-500" >Apply Filters</button>
    </div>
  </form>

  {% if search_query %}
    <p class="text-center text-gray-600">Results for "{{ search_query }}":</p>
  {% endif %}

  <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
    {% for books in sorted_books %}
    <div class="little_books_container">
      {% for book in books %}
      <article class="max-w-xs w-60 bg-white rounded-lg shadow-md m-4 p-6 book-card">
        <a href="{% url 'books:page' slug=book.slug %}" class="book_container">
          <img
            class="w-full h-64 object-cover rounded-t-lg"
            src="{{book.cover.url}}"
            alt="{{book.title}}"
            loading="lazy" >
          <div class="p-4 text-center">
            <h2 class="text-xl font-semibold text-gray-700">{{book.title}}</h2>
            <p class="text-gray-500">{{book.author}}</p>
            <p class="text-gray-600 mt-2">${{book.price}}</p>
          </div>
        </a>
      </article>
      {% endfor %}
    </div>
    {% endfor %}
  </div>
</section>
{% endblock  %}

books/templates/books/new_review.html
{% extends "layout.html" %} 

{% block title %}
    Review for {{book.title}} - Quill
{% endblock %}

{% block content %}
    <section class="container mx-auto p-8 text-center">
        <div class="mt-8">
            <h1 class="text-3xl font-bold text-gray-800 mb-6">Write a Review for {{ book.title }}</h1>
        </div>
        <form method="post" class="bg-white shadow-md rounded-lg p-6 max-w-lg mx-auto border-t-4 border-yellow-500">
            {%csrf_token%}
            <div class="row-review">
                {{ form.rating.label_tag }}
                <p class="buttons_fire2_0" style="width: 100px; position: static;">
                {{ form.rating }}
                </p>
            </div>
            <div>
                <p>{{ form.review_text.label_tag }}</p>
                <p>
                {{ form.review_text }}
                </p>
            </div>
            <div class="row-review">
                <p>
                {{ form.recommendation.label_tag }}
                </p>
                <p class="buttons_fire2_0" style="width: 100px; position: static;">
                {{ form.recommendation }}
                </p>
            </div>
            <button type="submit" class="inline-block bg-yellow-400 text-white font-semibold py-3 px-6 rounded-lg shadow-lg transition duration-300 hover:bg-yellow-500">Submit</button>
        </form>
    </section>
{% endblock  %}

books/templates/books/review_new.html
{% extends "layout.html" %} 

{% block title %}
    review
{% endblock %}

{% block content %}
    <section>
        <h1>review</h1>
    </section>
{% endblock  %}